### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by dchau360** [derek-shnosh/ztp-watcher#3]
The service ztp-watcher.service seems to fail with this error.

```
[root@ztp-cisco ztp-watcher]# systemctl status ztp-watcher.service
● ztp-watcher.service - FreeZTP Provisioning Watcher
   Loaded: loaded (/etc/systemd/system/ztp-watcher.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2020-09-24 13:58:21 EDT; 6s ago
  Process: 1573 ExecStart=/bin/bash -c cd /var/git/ztp-watcher; python3 ztp-watcher.py (code=exited, status=1/FAILURE)
 Main PID: 1573 (code=exited, status=1/FAILURE)

Sep 24 13:58:20 ztp-cisco systemd[1]: Started FreeZTP Provisioning Watcher.
Sep 24 13:58:21 ztp-cisco bash[1573]: Traceback (most recent call last):
Sep 24 13:58:21 ztp-cisco bash[1573]: File "ztp-watcher.py", line 9, in <module>
Sep 24 13:58:21 ztp-cisco bash[1573]: import yaml
Sep 24 13:58:21 ztp-cisco bash[1573]: ModuleNotFoundError: No module named 'yaml'
Sep 24 13:58:21 ztp-cisco systemd[1]: ztp-watcher.service: main process exited, code=exited, status=1/FAILURE
Sep 24 13:58:21 ztp-cisco systemd[1]: Unit ztp-watcher.service entered failed state.
Sep 24 13:58:21 ztp-cisco systemd[1]: ztp-watcher.service failed.
```

**Comment by dchau360** [comment]
I've also installed:
pip install pyyaml

**Comment by derek-shnosh** [comment]
@dchau360 this requires python3, are you sure your `pip` command isn't for python2 in your environment? You may need `pip3 install pyyaml` or `python3 -m pip install pyyaml`.

**Comment by dchau360** [comment]
Thank you this helped me install pyyaml, watchdog, and nornir but not having luck with the next dependency.

```
[root@ztp-cisco ztp-watcher]# python3 ztp-watcher.py
Traceback (most recent call last):
  File "ztp-watcher.py", line 15, in <module>
    from nornir.plugins.tasks.networking import netmiko_send_command, netmiko_send_config
ModuleNotFoundError: No module named 'nornir.plugins.tasks.networking'

[root@ztp-cisco ztp-watcher]# python3 -m pip install nornir.plugins.tasks.networking
WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
Collecting nornir.plugins.tasks.networking
  Could not find a version that satisfies the requirement nornir.plugins.tasks.networking (from versions: )
No matching distribution found for nornir.plugins.tasks.networking
```

**Comment by dchau360** [comment]
Ok i think i solved it.  It seems "nornir.plugins.tasks.networking" has been replaced with "nornir_netmiko".

I also had to edit /var/git/ztp-watcher/ztp-watcher.py and replace the same entry.

**Comment by derek-shnosh** [comment]
@dchau360 yeah if you're running Nornir v3+ the utils structure changed very recently, I haven't updated the script to accommodate that yet.

**Comment by dchau360** [comment]
So it seems to be running now and monitors for provisioned switches but it doesn't seem to download the .bin and upgrade. 

```
cat /etc/ztp/logs/ztpwatcher.log
2020/09/24 03:46:07 PM -- OK - Configuration file found (ztpconfig.yaml).
2020/09/24 03:46:07 PM -- WARNING: Post provisioning configuration file not found (/var/git/ztp-watcher/postcfg.txt).
2020/09/24 03:46:08 PM -- ZTP Watcher fully loaded and running.
2020/09/24 03:47:52 PM -- ZTP Watcher stopped (keyboard interrupt).
2020/09/24 03:49:55 PM -- OK - Configuration file found (ztpconfig.yaml).
2020/09/24 03:49:55 PM -- WARNING: Post provisioning configuration file not found (/var/git/ztp-watcher/postcfg.txt).
2020/09/24 03:49:55 PM -- ZTP Watcher fully loaded and running.
2020/09/24 03:55:55 PM -- OK - Configuration file found (ztpconfig.yaml).
2020/09/24 03:55:55 PM -- WARNING: Post provisioning configuration file not found (/var/git/ztp-watcher/postcfg.txt).
2020/09/24 03:55:55 PM -- ZTP Watcher fully loaded and running.
2020/09/24 04:01:52 PM -- New file detected: DEFAULT_VALUES_10.32.132.160__merged.cfg
```

```
cat ztpconfig.yaml
# Where to store the log file for ZTP Watcher.
logfile: /etc/ztp/logs/ztpwatcher.log

# Location of FreeZTP custom merged-config files, must match path from the
# `ztp set logging merged-config-to-custom-file` path.
watch_dir: /etc/ztp/logs/merged/

# Use `dns` or provisioning `ip` for SSH connection.
# Use 'parse' to parse FreeZTP merged-config file for an IP address.
ssh_method: ip

# Enter name of file that contains post provisioning configuration, or type
# 'False' (without quotes) if there is none.
post_cfg: /var/git/ztp-watcher/postcfg.txt

# Enter path to push the final configuration to the TFTP server after
# completion, or type 'False' (without quotes).
cfg_push: /complete/

# IP address of TFTP server hosting files and name of image file to copy.
tftpaddr: 10.32.132.4
imgfile: 2960x-universalk9-mz.152-7.E2.bin

# Username and password used to authenticate to switches.
username: admin
password: password123

# SSH testing variables.
ssh_initialwait: 10
ssh_timeout: 7
ssh_retrywait: 5
ssh_maxattempts: 15
```

_Edited to format_

**Comment by derek-shnosh** [comment]
@dchau360 is there nothing else in the log.... once the new file is detected, it should kick off the `test_ssh` function.

Can you give me the output of `ztp show config | grep merged-config-to-custom-file`

**Comment by dchau360** [comment]
```
[root@ztp-cisco ztp-watcher]# ztp show config | grep merged-config-to-custom-file
ztp set logging merged-config-to-custom-file '/etc/ztp/logs/merged/{{keystore_id}}_{{ipaddr}}_{{idarray|join("-")}}_merged.cfg'
```

**Comment by derek-shnosh** [comment]
The custom file *must* begin with `{{keystore_id}}_{{ipaddr}}`; you're missing the underscore `_` between there, this is crucial as this is how the script parses the switches hostname `keystore_id` and the IP address it received from FreeZTP `ipaddr`. See [lines 71-72](https://github.com/derek-shnosh/ztp-watcher/blob/dcaa38fc23caf7fb0ae48ecdd530b240bcb5a078/ztp-watcher.py#L71-72).

```bash
ztp set logging merged-config-to-custom-file '/etc/ztp/logs/merged/{{keystore_id}}_{{ipaddr}}_{{idarray|join("-")}}_merged.cfg'
```

**Comment by dchau360** [comment]
So weird...my copy and paste does have the underscore. It's just not displaying it on this comment but when i edit the comment is shows.

```
[root@ztp-cisco ztp-watcher]# ztp show config | grep merged-config-to-custom-file
ztp set logging merged-config-to-custom-file '/etc/ztp/logs/merged/{{keystore_id}}_{{ipaddr}}_{{idarray|join("-")}}_merged.cfg'
```

**Comment by derek-shnosh** [comment]
Ahhh, ok, looks like you might have it right, but since you didn't initially format using back-ticks or a code block the `_` underscores applied markdown italic formatting.

**Comment by derek-shnosh** [comment]
While re-reading [your log output](https://github.com/derek-shnosh/ztp-watcher/issues/3#issuecomment-698640616), I can see that it parsed the `keystore_id` as `DEFAULT_VALUES`... You're going to want to remove the underscore from that, because as it stands this is how its parsing...

`keystore_id` = `DEFAULT`
`ipaddr` = `VALUES`

In my typical deployment I use an external CSV keystore and external templates with the following format...

```csv
keystore_id,association,idarray_1
HOST-NAME,TEMPLATE,SERIALNUM
```

The [FreeZTP readme.md](https://github.com/PackeTsar/freeztp/blob/latest/README.md) file has an explanation on the external keystores and templates.

**Comment by dchau360** [comment]
I'm sorry i don't follow. Remove underscore from which file?

**Comment by derek-shnosh** [comment]
Based on your ztp config line, the following line from your log says that the switch's `keystore_id` is "`DEFAULT_VALUES`"

```
2020/09/24 04:01:52 PM -- New file detected: DEFAULT_VALUES_10.32.132.160__merged.cfg
```

So you need to change that to something else that _doesn't_ have an underscore `_` in it... familiarize yourself more with the FreeZTP documentation and it'll make more sense.

**Comment by dchau360** [comment]
I'm still a bit unsure about the external keystores and templates but i did set a keystore and hostname which got provisioned.

```
[root@ztp-cisco ~]# cat /etc/ztp/logs/ztpwatcher.log
2020/09/24 05:35:09 PM -- OK - Configuration file found (ztpconfig.yaml).
2020/09/24 05:35:09 PM -- WARNING: Post provisioning configuration file not found (/var/git/ztp-watcher/postcfg.txt).
2020/09/24 05:35:09 PM -- ZTP Watcher fully loaded and running.
2020/09/24 05:40:36 PM -- New file detected: FJC2341W1ZC_10.32.132.161__merged.cfg
```

Yet it still didn't update the firmware as i was hoping. I've uploaded my ztp.cfg and ztpconfig.yaml to [https://www.dropbox.com/sh/iy1hjdzuyn03gny/AADf_wzAiAZz50AQxGinkPKLa?dl=0](url)

Thank so much for the help.

**Comment by derek-shnosh** [comment]
Change line 14 in your `ztpconfig.yaml` file as follows (if you don't need post config tasks).

```yaml
post_cfg: False
```

.... and lines 29-32 as follows.

```yaml
ssh_initialwait: 10
ssh_timeout: 5
ssh_retrywait: 3
ssh_maxattempts: 5
```

Then, instead of running the script via `systemctl` browse to where you have it saved and type `python3 ztp-watcher.py` so you can watch the log *live*

```bash
sudo systemctl stop ztp-watcher
cd /var/www/git/ztp-watcher
sudo python3 ztp-watcher.py
```

After the new file is detected, it will wait 10 seconds (`ssh_initialwait`) then try to establish and SSH connection with a timeout of 5 seconds (`ssh_timeout`), if it is unsuccessful after 5 seconds, it will wait 3 seconds (`ssh_retrywait`)... it will try 5 (`ssh_maxatempts`) more times and should give a log message stating it couldn't connect to the switch (if unsuccessful).

**Comment by dchau360** [comment]
So I finally had a chance to try again today. It still doesn't seem to do update the firmware as I hoped. I confirmed that i was able to ssh to that IP with the same login as in the yaml file.
```
2020/10/09 09:47:47 AM -- OK - Configuration file found (ztpconfig.yaml).
2020/10/09 09:47:47 AM -- ZTP Watcher fully loaded and running.
2020/10/09 09:58:19 AM -- New file detected: FJC2343W076_10.32.132.247__merged.cfg
```

**Comment by dchau360** [comment]
Retrying. Had the wrong firmware file name in the yaml file.

**Comment by dchau360** [comment]
Yeah, still dont see anything else happening after new file detected.

**Comment by derek-shnosh** [comment]
@dchau360 - apologies for the delayed response. The fact that the file is being detected but nothing is happening afterwards is definitely odd. The `Handler` class should use the `threading` module to kick off the `test_ssh` function, which should provide some form of feedback; my guess is that either the `threading` or `socket` module is hanging/crashing.

Have you tried running the script to watch it, instead of letting `systemctl` run it? This *may* give more feedback as you'll be watching the script run, versus just viewing the logs after the fact.

```bash
sudo systemctl stop ztp-watcher
cd /var/www/git/ztp-watcher
sudo python3 ztp-watcher.py
```

**Comment by dchau360** [comment]
I did and it was the same result. Did not see any attempts at ssh.

**Comment by derek-shnosh** [comment]
Just took a few minutes to read through the logic of the script (its been a while since I wrote it initially).

You're getting the `New file detected...` log message meaning the `test_ssh` function should be called which should provide a `Verifying SSH reachability` log message before doing much of anything else. Line 77-78 should use the `threading` module to call on the `test_ssh` function, but it seems that's not happening. 

https://github.com/derek-shnosh/ztp-watcher/blob/701f2b3810741ac2f9fa44fab7deec40a3d6d79f/ztp-watcher.py#L77-L78

I'm not sure how to help from here, if I had access to the environment I'd do some good old `print()` debug to troubleshoot.

You can try replacing lines 69 - 78 with this to hopefully find out where it's failing...

```python
            if not any(str in filename for str in ignorefiles):
                Logger(f'New file detected: {filename}')
                hostname = filename.split('_')[0]
                Logger(f'Switch hostname: {hostname}')
                hostaddr = filename.split('_')[1]
                Logger(f'Switch address: {hostaddr}')
                if ssh_method == 'parse':
                    time.sleep(2)
                    config = open(newfile).read()
                    ipaddr = re.search(r'ip\saddress\s([\d\.]+)', config).group(1) or ''
                    Logger(f'Parsed IP address: {ipaddr}')
                Logger('Building thread to call test_ssh function...')
                x = threading.Thread(target=self.test_ssh, args=(hostname, hostaddr, ipaddr))
                Logger('Starting thread...')
                x.start()
                Logger('Thread should\'ve started...')
```

I'd expect to see the following in the logs...

```
2020/10/09 09:47:47 AM -- OK - Configuration file found (ztpconfig.yaml).
2020/10/09 09:47:47 AM -- ZTP Watcher fully loaded and running.
2020/10/09 09:58:19 AM -- New file detected: FJC2343W076_10.32.132.247__merged.cfg
2020/10/09 09:58:19 AM -- Switch hostname: <hostname>
2020/10/09 09:58:19 AM -- Switch address: <dhcp address>
2020/10/09 09:58:19 AM -- Building thread to call test_ssh function...
2020/10/09 09:58:19 AM -- Starting thread...
2020/10/09 09:58:19 AM -- Thread should've started...
```
